name: "CI Render Linux"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: 0.0.1
  EXPORT_NAME: source_code
  OPENTOONZ_BINARY : OpenToonz-1.4.0-morevna-2020.06.14-linux64-b6177.appimage
  RENDERCHAN_ENVDIR : /home/runner/work/RenderChan/env/linux/
jobs:

  export-linux:
    name: RenderChan UwU
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Dependencies
        run: | 
          sudo apt update -y
          sudo apt install blender krita ffmpeg
          sudo snap install opentoonz-morevna 
          cd projects && git clone https://github.com/Sam2much96/Dystopia   
          wget -P ${RENDERCHAN_ENVDIR} https://github.com/morevnaproject-org/opentoonz/releases/download/v1.4.0-morevna/${OPENTOONZ_BINARY}
          chmod +x ${RENDERCHAN_ENVDIR}/${OPENTOONZ_BINARY}
          cd ${RENDERCHAN_ENVDIR} && touch tcomposer.txt  
          sed -i '1s|^|'OpenToonz-1.4.0-morevna-2020.06.14-linux64-b6177.appimage'\n|' tcomposer.txt
          ls -al
          cd .. && ls -al
          cd .. && ls -al
          cd .. && ls -al
          cd work && ls -al
          cd ..
          

      - name: RenderChan (^U^)/
        run: |
          cd projects && ls  
          cd ../bin  
          ./renderchan "../projects/Dystopia/project.blend"

      - name: Linux Build
        run: |

          ls -al
      - name: Upload Render
        uses: actions/upload-artifact@v1
        with:
          name: Video.avi
          path: projects/Dystopia/render/project.blend.avi
