name: "ci export Linux"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: 0.0.1
  EXPORT_NAME: source_code
  OPENTOONZ_BINARY : OpenToonz-1.4.0-morevna-2020.06.14-linux64-b6177.appimage
 
jobs:

  export-linux:
    name: Fetch
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Dependencies
        run: |
          sudo apt update -y
          sudo apt install blender krita 
          sudo snap install opentoonz-morevna 
          cd RenderChan/projects && git clone https://github.com/Sam2much96/Dystopia  
          cd ../env/linux 
          wget -P . https://github.com/morevnaproject-org/opentoonz/releases/download/v1.4.0-morevna/${OPENTOONZ_BINARY}
          export RENDERCHAN_ENVDIR = ~/RenderChan/env/linux/${OPENTOONZ_BINARY}

      - name: Render
        run: |
          ls -al 
          cd ..
          cd bin 
          ./renderchan "../projects/Dystopia/project.blend"

      - name: Linux Build
        run: |

          ls -al
      - name: Upload 
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
