name: "CI Render Linux"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: 0.0.1
  EXPORT_NAME: source_code
  OPENTOONZ_BINARY : OpenToonz-1.4.0-morevna-2020.06.14-linux64-b6177.appimage
  KRITA_BINARY : krita-5.0.2-x86_64.appimage
  RENDERCHAN_ENVDIR : /home/runner/work/RenderChan/RenderChan/env/linux/
jobs:

  export-linux:
    name: RenderChan UwU
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Dependencies
        run: | 
          sudo apt update -y
          sudo apt install blender ffmpeg krita
          cd projects && git clone https://github.com/Sam2much96/Dystopia   
          wget -P ${RENDERCHAN_ENVDIR} https://github.com/morevnaproject-org/opentoonz/releases/download/v1.4.0-morevna/${OPENTOONZ_BINARY}
          wget -P ${RENDERCHAN_ENVDIR} https://download.kde.org/stable/krita/5.0.2/${KRITA_BINARY}
          sudo chmod +x ${RENDERCHAN_ENVDIR}/${OPENTOONZ_BINARY}
          sudo chmod +x ${RENDERCHAN_ENVDIR}/${KRITA_BINARY}
          cd ${RENDERCHAN_ENVDIR}  
          touch tcomposer.txt  
          sed -i '1s|^|'/home/runner/work/RenderChan/RenderChan/env/linux/OpenToonz-1.4.0-morevna-2020.06.14-linux64-b6177.appimage'\n|' tcomposer.txt
          touch krita.txt
          sed -i '1s|^|'/usr/bin/krita'\n|' krita.txt
          ls -al
          cd ../..

      - name: RenderChan \(^U^)/
        run: |      
          cd bin  
          chmod +x render-test.sh
          ./render-test.sh
   
      - name: Linux Build
        run: |

          ls -al
      - name: Upload Render
        uses: actions/upload-artifact@v1
        with:
          name: Video.avi
          path: projects/Dystopia/render/project.blend.avi
